metadata:
  name: "Feature Template"
  id: "template"
  description: "Template base para crear nuevos features"
  created: "2026-01-15"
  status: "template"

roles:
  - id: planner
    name: "Planner"
    description: "Define el feature, crea tareas, toma decisiones arquitectónicas"

  - id: developer
    name: "Developer"
    description: "Implementa el feature según la definición"

  - id: qa
    name: "QA/Reviewer"
    description: "Revisa implementación, documenta problemas, valida calidad"

stages:
  - id: planning
    name: "Planning & Definition"
    owner: planner
    workspace: "./ai/features/{FEATURE_ID}/"
    permissions:
      read:
        - "./ai/**"
      write:
        - "./ai/features/{FEATURE_ID}/definition.md"
        - "./ai/features/{FEATURE_ID}/tasks.md"
        - "./ai/features/{FEATURE_ID}/planner_state.md"
    dependencies: []
    parallel: false
    state_file: "planner_state.md"
    outputs:
      - "definition.md"
      - "tasks.md"

  - id: implementation
    name: "Implementation"
    owner: developer
    workspace: "./src/"
    permissions:
      read:
        - "./ai/**"
        - "./src/**"
      write:
        - "./src/**"
        - "./ai/features/{FEATURE_ID}/dev_state.md"
    dependencies: ["planning"]
    parallel: false
    state_file: "dev_state.md"
    outputs:
      - "Código implementado en ./src/"

  - id: review
    name: "QA & Review"
    owner: qa
    workspace: "./"
    permissions:
      read:
        - "./ai/**"
        - "./src/**"
        - "./tests/**"
      write:
        - "./ai/features/{FEATURE_ID}/qa_state.md"
        - "./ai/features/{FEATURE_ID}/review.md"
    dependencies: ["implementation"]
    parallel: false
    state_file: "qa_state.md"
    outputs:
      - "review.md"

validation:
  required_files:
    - "definition.md"
    - "tasks.md"
    - "planner_state.md"
  state_format: "markdown"
  allow_parallel_writes: false

# Instrucciones por Stage

instructions:
  planning:
    prompt: |
      Eres el PLANNER. Tu trabajo es:

      1. Leer el feature request del usuario
      2. Crear `definition.md` con:
         - Objetivo del feature
         - Requisitos funcionales
         - Criterios de aceptación
         - Consideraciones técnicas
      3. Crear `tasks.md` con lista de tareas específicas
      4. Actualizar `planner_state.md` con estado: COMPLETED

      NO implementes código. Solo planifica y define.

  implementation:
    prompt: |
      Eres el DEVELOPER. Tu trabajo es:

      1. Leer `definition.md` y `tasks.md`
      2. Implementar el código necesario en `./src/`
      3. Actualizar `dev_state.md` con:
         - Tareas completadas
         - Archivos modificados
         - Decisiones técnicas tomadas
         - Bloqueos o dudas (estado: BLOCKED)

      Sigue la definición estrictamente. Si algo no está claro, marca BLOCKED.

  review:
    prompt: |
      Eres el QA/REVIEWER. Tu trabajo es:

      1. Leer `definition.md` para entender expectativas
      2. Revisar código implementado
      3. Verificar que cumple criterios de aceptación
      4. Crear `review.md` con:
         - ✅ Aspectos que cumplen
         - ❌ Problemas encontrados
         - 💡 Sugerencias de mejora
      5. Actualizar `qa_state.md` con estado: APPROVED o REJECTED

      NO fixes código tú mismo. Reporta problemas al Developer.
