#!/bin/bash
# generate_context.sh - Generate context.md from project analysis
# Combines output from other tools to create context.md
#
# Usage: ./generate_context.sh [project_name]
#
# Output: context.md content to stdout

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_PATH="$(pwd)"
PROJECT_NAME="${1:-$(basename "$PROJECT_PATH")}"
DATE=$(date +%Y-%m-%d)

# Gather information using other tools
STRUCTURE=$("$SCRIPT_DIR/analyze_structure.sh" 2>/dev/null || echo "{}")
FRAMEWORKS=$("$SCRIPT_DIR/detect_framework.sh" 2>/dev/null || echo "{}")
DEPENDENCIES=$("$SCRIPT_DIR/read_dependencies.sh" 2>/dev/null || echo "{}")

# Extract key information
HAS_BACKEND=$(echo "$STRUCTURE" | grep -o '"has_backend": *[^,}]*' | grep -o 'true\|false' || echo "false")
HAS_FRONTEND=$(echo "$STRUCTURE" | grep -o '"has_frontend": *[^,}]*' | grep -o 'true\|false' || echo "false")
HAS_AI_WORKFLOW=$(echo "$STRUCTURE" | grep -o '"has_ai_workflow": *[^,}]*' | grep -o 'true\|false' || echo "false")

cat << EOF
# Project Context

> Auto-generated by AI Consultant on $DATE
> This file provides Claude with awareness of the project state and available resources.

## Project Overview

| Field | Value |
|-------|-------|
| **Name** | $PROJECT_NAME |
| **Path** | $PROJECT_PATH |
| **Generated** | $DATE |

## Tech Stack Detection

### Backend
EOF

if [ "$HAS_BACKEND" = "true" ]; then
    echo "- **Detected**: Yes"
    # Extract backend frameworks
    echo "$FRAMEWORKS" | grep -o '"name":"[^"]*"' | head -3 | sed 's/"name":"\([^"]*\)"/- Framework: \1/'
else
    echo "- **Detected**: No backend directory found"
fi

cat << EOF

### Frontend
EOF

if [ "$HAS_FRONTEND" = "true" ]; then
    echo "- **Detected**: Yes"
else
    echo "- **Detected**: No frontend directory found"
fi

cat << EOF

## Directory Structure

\`\`\`
$PROJECT_PATH/
EOF

# List directories (max 2 levels)
find "$PROJECT_PATH" -maxdepth 2 -type d ! -path '*/\.*' ! -path '*/node_modules*' ! -path '*/vendor*' 2>/dev/null | \
    sort | while read -r dir; do
    relpath="${dir#$PROJECT_PATH}"
    if [ -n "$relpath" ]; then
        depth=$(echo "$relpath" | tr -cd '/' | wc -c)
        indent=""
        for ((i=0; i<depth; i++)); do
            indent="$indent  "
        done
        basename=$(basename "$dir")
        echo "${indent}├── $basename/"
    fi
done

cat << EOF
\`\`\`

## Available Workflows

| Workflow | Description | Use Case |
|----------|-------------|----------|
| \`default\` | Full cycle: plan → implement → review | Standard features |
| \`task-breakdown\` | Detailed planning only | Complex features |
| \`implementation-only\` | Implementation without planning | After task-breakdown |

## Roles

| Role | File | Responsibility |
|------|------|----------------|
| Planner | \`.ai/workflow/roles/planner.md\` | Architecture & specs |
| Backend | \`.ai/workflow/roles/backend.md\` | API & business logic |
| Frontend | \`.ai/workflow/roles/frontend.md\` | UI & UX |
| QA | \`.ai/workflow/roles/qa.md\` | Testing & validation |

## Quick Commands

\`\`\`bash
# AI Consultation
./.ai/workflow/scripts/ai_consultant.py

# Start workflow
./.ai/workflow/scripts/workflow.sh start <feature-id> <workflow>

# Individual role
./.ai/workflow/scripts/workflow.sh role <role> <feature-id>

# Validate
./.ai/workflow/scripts/workflow.sh validate <feature-id>
\`\`\`

## AI Recommendations

Based on detected structure:
EOF

if [ "$HAS_BACKEND" = "true" ] && [ "$HAS_FRONTEND" = "true" ]; then
    echo "- **Project Type**: Full-stack (backend + frontend)"
    echo "- **Recommended Workflow**: \`task-breakdown\` for complex features"
    echo "- **Parallel Execution**: Backend and Frontend can work in parallel"
elif [ "$HAS_BACKEND" = "true" ]; then
    echo "- **Project Type**: Backend-only"
    echo "- **Recommended Workflow**: \`default\` for most features"
elif [ "$HAS_FRONTEND" = "true" ]; then
    echo "- **Project Type**: Frontend-only"
    echo "- **Recommended Workflow**: \`default\` for most features"
else
    echo "- **Project Type**: Unknown or new project"
    echo "- **Recommendation**: Run \`ai_consultant.py --new-project\` to set up"
fi

cat << EOF

---

**Generated by**: generate_context.sh
**Last Updated**: $DATE
EOF
